package com.example;
// Generated 02-Mar-2017 22:51:14 by Hibernate Tools 3.5.0.Final

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int studentId;
	private String name;
	private int marks;

	public Student()
	{
	}

	public Student(int studentId, String name, int marks)
	{
		this.studentId = studentId;
		this.name = name;
		this.marks = marks;
	}

	public int getStudentId()
	{
		return this.studentId;
	}

	public void setStudentId(int studentId)
	{
		this.studentId = studentId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public int getMarks()
	{
		return this.marks;
	}

	public void setMarks(int marks)
	{
		this.marks = marks;
	}

	@Override
	public String toString()
	{
		return "Student [studentId=" + studentId + ", name=" + name + ", marks=" + marks + "]";
	}

}
